---
- name: Disable selinux
  selinux: state=disabled
  when: selinux_enabled == true

- name: Disable sshd strict modes
  lineinfile:
      backrefs: yes
      dest: /etc/ssh/sshd_config
      regexp: "^#StrictModes yes"
      line: "StrictModes no"
  notify: restart sshd

- name: Install Pulp dnf repository
  get_url:
      url: https://repos.fedorapeople.org/repos/pulp/pulp/fedora-pulp.repo
      dest: /etc/yum.repos.d/fedora-pulp.repo

- name: Enable Pulp 2.7 beta repository
  command: dnf config-manager --set-enabled pulp-2.7-beta
  when: pulp_27_beta_repo_enabled == false

# This and its related fact should go away when we do have an f23 build, since it'll be a noop at that point
- name: Rejigger the repo file if fedora 23 builds aren't available
  replace:
      dest: /etc/yum.repos.d/fedora-pulp.repo
      regexp: 'fedora-\$releasever'
      replace: fedora-22
  when: not pulp_27_beta_f23_repo_available and
        ansible_distribution == 'Fedora' and
        ansible_distribution_version == '23'

# These can go away when https://fedorahosted.org/spin-kickstarts/ticket/59 is fixed
- stat:
      path: /etc/sudoers.d/vagrant-nopasswd
  name: Detect vagrant sudoers file
  register: vagrant_nopasswd
- lineinfile:
      dest: "{{ vagrant_nopasswd.stat.path }}"
      regexp: '^vagrant'
      line: 'vagrant ALL=(ALL) NOPASSWD: ALL'
      validate: 'visudo -cf %s'
      mode: 0440
  when: vagrant_nopasswd.stat.exists
  name: Rejigger vagrant sudoers file

- name: Install packages
  dnf: name={{ item }} state=present
  with_items:
      - git
      - dstat
      - fpaste
      - gcc
      - iotop
      - jnettop
      - koji
      - python-django-bash-completion
      - python-gofer-qpid
      - python-ipdb
      - python-qpid
      - python-qpid-qmf
      - python-setuptools
      - python-sphinx
      - python-virtualenvwrapper
      - python2-rpdb
      - redhat-lsb-core
      - rpm-build
      - telnet
      - tito
      - yum-utils

- copy: src=bashrc dest=/home/{{ ansible_env.SUDO_USER }}/.bashrc
- copy: src=drop_database.js dest=/home/{{ ansible_env.SUDO_USER }}/drop_database.js
- copy: src=motd dest=/etc/motd

- include: debug.yml
  # set this to true in extra vars to enable debug-related tasks
  when: pulp_dev_debug
