sudo: false
language: python
python:
    - "3.4"
    - "3.5"
addons:
    postgresql: "9.3"
install:
    - "pip install -r test_requirements.txt"
    - "pushd app/ && python setup.py develop && popd"
    - "pushd common/ && python setup.py develop && popd"
    - "pushd exceptions/ && python setup.py develop && popd"
    - "pushd plugin/ && python setup.py develop && popd"
    - "pushd tasking/ && python setup.py develop && popd"
before_script:
    - psql -U postgres -c "CREATE USER pulp WITH SUPERUSER LOGIN;"
    - psql -U postgres -c "CREATE DATABASE pulp OWNER pulp;"
script:
    # flake8 the diff
    - "git diff HEAD^ '*.py' | flake8 --diff --config flake8.cfg"
    # tests can't run without migrations being made
    - "python manage.py makemigrations pulp_app"
    # run the tests!
    - "python manage.py test app"
