sudo: false
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.5"
    - "3.6"
addons:
    # postgres versions provided by el7 RHSCL (lowest supportable version)
    postgresql: "9.5"
services:
    - postgresql
install:
    # dev_requirements should not be needed for testing; don't install them to make sure
    - "pip install -r test_requirements.txt"
    - "pushd common/ && python setup.py develop && popd"
    - "pushd platform/ && python setup.py develop && popd"
    - "pushd plugin/ && python setup.py develop && popd"
before_script:
    - psql -U postgres -c "CREATE USER pulp WITH SUPERUSER LOGIN;"
    - psql -U postgres -c "CREATE DATABASE pulp OWNER pulp;"
script:
    # flake8 the diff
    - "git diff HEAD^ '*.py' | flake8 --diff --config flake8.cfg"
    # tests can't run without migrations being made
    - "python manage.py makemigrations pulp_app"
    # chain these so we don't try to run tests if the db reset fails
    - "platform/pulpcore/app/db-reset.sh && python manage.py test"
