---
- name: Install basic packages
  dnf: name={{ item }} state=present
  with_items:
      - bash-completion
      - vim-enhanced
      - screen

- name: Install packages requires to gather Pulp facts
  dnf: name={{ item }} state=present
  with_items:
      - rpm-build

- name: Gathering Pulp facts
  pulp_facts:
