---
- name: Install dnf and deltarpm
  yum: name={{ item }} state=latest
  with_items:
      - dnf
      - deltarpm

- name: System update
  dnf: name=* state=latest

- name: Install common packages
  dnf: name={{ item }} state=latest
  with_items:
      - bash-completion
      - vim-enhanced
