---
- hosts: all
  become: true
  become_method: sudo
  vars:
  roles:
    - core

- hosts: dev
  become: true
  become_method: sudo
  vars:
  roles:
    - db
    - qpidd
    - dev
    - lazy
    - pulp_ca
